Repository andresgongora/synth-shell, pull requests merged in 2019-06, with the labels that each got.

#71 Fix format error in printTop
  terminal/status.sh
Labels: bug

#94 Show Current Branch Name
  AUTHORS.md
  doc/screenshot.png
  doc/screenshot_old.png
  terminal/fancy-bash-prompt.sh
Labels: feature request

#99 Features/git-info
  AUTHORS.md
  common/color.sh
  common/shorten_path.sh
  config_templates/fancy-bash-prompt.config
  doc/coding_style.md
  install/install.sh
  terminal/fancy-bash-prompt.sh
Labels: enhancement, status.sh
